language: node_js
node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
cache:
  directories:
    - "node_modules"
before_script:
  - npm run check-security
  - npm run lint-ci
  - npm run clean-build
  - npm run build-ci