authenticators:
  local:
    module: identity-desk-mock-local
    source: npm
    version: ^0.1.0
    successRedirect: '/restricted'
database:
  dialect: sqlite
  logging: false
  url: $DATABASE_URL
session:
  keys: $SESSION_KEYS